/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface CandidateHeader {
        "candidateInfo": CandidateDetails;
        "reqId": string;
    }
    interface MyComponent {
    }
}
declare global {
    interface HTMLCandidateHeaderElement extends Components.CandidateHeader, HTMLStencilElement {
    }
    var HTMLCandidateHeaderElement: {
        prototype: HTMLCandidateHeaderElement;
        new (): HTMLCandidateHeaderElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLElementTagNameMap {
        "candidate-header": HTMLCandidateHeaderElement;
        "my-component": HTMLMyComponentElement;
    }
}
declare namespace LocalJSX {
    interface CandidateHeader {
        "candidateInfo"?: CandidateDetails;
        "onOpenJobDescription"?: (event: CustomEvent<boolean>) => void;
        "reqId"?: string;
    }
    interface MyComponent {
    }
    interface IntrinsicElements {
        "candidate-header": CandidateHeader;
        "my-component": MyComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "candidate-header": LocalJSX.CandidateHeader & JSXBase.HTMLAttributes<HTMLCandidateHeaderElement>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
        }
    }
}
